"""adadd the pitch class model

Revision ID: 716c2fe37189
Revises: a97244556a5d
Create Date: 2018-01-02 11:06:11.729720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '716c2fe37189'
down_revision = 'a97244556a5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pitch', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pitch')
    # ### end Alembic commands ###
