"""add a user id column

Revision ID: a97244556a5d
Revises: cba5822b831a
Create Date: 2018-01-02 09:13:49.093304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a97244556a5d'
down_revision = 'cba5822b831a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch', 'user_id')
    # ### end Alembic commands ###
