"""test migration for the comment model

Revision ID: b5a788ed956f
Revises: c816461a2efd
Create Date: 2018-01-04 06:36:12.892089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a788ed956f'
down_revision = 'c816461a2efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment', sa.String(), nullable=True))
    op.add_column('comments', sa.Column('comment_title', sa.String(), nullable=True))
    op.drop_column('comments', 'pitch_title')
    op.drop_column('comments', 'pitch_comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('pitch_comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('pitch_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'comment_title')
    op.drop_column('comments', 'comment')
    # ### end Alembic commands ###
