"""add the user id column in the with the help of foreign keys and relationships

Revision ID: c13247218c08
Revises: 716c2fe37189
Create Date: 2018-01-03 02:00:47.752412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c13247218c08'
down_revision = '716c2fe37189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'pitch', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitch', type_='foreignkey')
    # ### end Alembic commands ###
